.\" Copyright 2002 Paul Thompson <set@pobox.com>
.\" Copyright 2014 Pali Rohár <pali.rohar@gmail.com>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" References consulted:
.\"     udftools src
.\"
.TH MKUDFFS 8 "udftools" "System Management Commands"

.SH NAME
mkudffs \- create an UDF filesystem

.SH SYNOPSIS
.BI "mkudffs [ switches ] " device " [ " blocks-count " ] "

.SH DESCRIPTION
.B mkudffs
is used to create a UDF filesystem on a device (usually a disk).
\fIdevice\fP is the special file corresponding to the device (e.g.
\fI/dev/hdX\fP). \fIblocks-count\fP is the number of blocks on the device.
If omitted,
.B mkudffs
automagically figures the file system size. The order of options matters.
Ident string options must be first and options to override default
settings implied by the media-type or UDF revision should be after
the option they are overriding.

.SH OPTIONS
.TP
.B \-h,\-\-help
Display the usage and list of options.

.TP
.BI \-l,\-\-label= " label "
Specify the UDF label. UDF label is synonym for specifying both \-\-lvid and
\-\-vid options. If omitted,
.B mkudffs
label is LinuxUDF.

.TP
.BI \-u,\-\-uuid= " uuid "
Specify the UDF uuid. Must be exactly 16 hexadecimal lowercase digits and is
used for first 16 characters of \-\-fullvsid option. If omitted,
.B mkudffs
uuid is generated from local time and random number.

.TP
.BI \-b,\-\-blocksize= " block-size "
Specify the size of blocks in bytes. Valid block size vales are 512, 1024,
2048 and 4096 bytes per block. If omitted,
.B mkudffs
block-size is set to device logical block (sector) size. If it is unknown
then for \fB\-\-media\-type\fP=\fIhd\fP is used block-size 512 and for other
media types 2048.

.TP
.BI \-r,\-\-udfrev= " udf-revision "
Specify the udf revision to use. Valid revisions are 0x0201, 0x0200, 0x0150,
and 0x0102. If omitted,
.B mkudffs
udf-revision is 0x0201. The hex values represent the ISO/IEC 13346 standard
version numbers: e.g. the 0x0201 refers to 2.01 (March 15, 2000) which is
mainly a bugfix release to UDF 2.00.

.TP
.BI \-\-lvid= " logical-volume-ident "
Specify the logical volume identifier. If omitted,
.B mkudffs
logical-volume-ident is LinuxUDF.

.TP
.BI \-\-vid= " volume-ident "
Specify the volume identifier. If omitted,
.B mkudffs
volume-ident is LinuxUDF.

.TP
.BI \-\-vsid= " volume-set-ident "
Specify the 17.-127. character of volume set identifier. If omitted,
.B mkudffs
volume-set-ident is LinuxUDF.

.TP
.BI \-\-fsid= " file-set-ident "
Specify the file set identifier. If omitted,
.B mkudffs
file-set-ident is LinuxUDF.

.TP
.BI \-\-fullvsid= " full-volume-set-ident "
Specify the volume set identifier. Overwrite previous \-\-uuid and
\-\-vsid options.

.TP
.BI \-\-uid= " uid "
Specify the uid of the root (/) directory. If omitted,
.B mkudffs
uid is 0.

.TP
.BI \-\-gid= " gid "
Specify the gid of the root (/) directory. If omitted,
.B mkudffs
gid is 0.

.TP
.BI \-\-bootarea= " fill "
Specify how to fill UDF boot area which is first 32kB of disk and is not
used by UDF itself. Option \fImbr\fP make sense only when running mkudffs
on whole disk, not on just one partition. Valid options are:
.RS 1.2i
.TP 1.6i
preserve
preserve existing UDF boot area, do not touch it (default for media type
different from hd)
.TP
erase
erase existing UDF boot area, fill it by zeros (default for hd media type)
.TP
mbr
put MBR with one partition which starts at sector 0 (includes MBR itself)
and spans whole disk device (needed for non-removable hard disks used on
Microsoft Windows systems)
.RE

.TP
.BI \-\-strategy= " strategy "
Specify the allocation strategy to use. Valid strategies are 4 and 4096.
If omitted,
.B mkudffs
strategy is based on the \fImedia-type\fP.

.TP
.BI \-\-spartable= " spartable-number "
Specify the number of sparing tables to write to disc. Valid numbers are 1 \- 4.
This option implies \fB\-\-media\-type\fP=\fIcdrw\fP.

.TP
.BI \-m,\-\-media\-type= " media\-type "
Specify the media type. Valid media types are:
.RS 1.2i
.TP 1.6i
hd (default)
hard drive
.TP
dvd
DVD (Digital Versatile Disc)
.TP
dvdram
DVD\-RAM (Digital Versatile Disc\-Random Access Memory)
.TP
dvdrw
DVD\-RW (DVD Read\-Write)
.TP
dvdr
DVD\-R (DVD Recordable)
.TP
worm
WORM (Write Once Ready Many)
.TP
mo
MO (Magneto Optical)
.TP
cdrw
CD\-RW (CD Read\-Write)
.TP
cdr
CD\-R (CD Recordable)
.TP
cd
CD\-ROM (CD Read\-Only Memory)
.RE

.TP
.BI \-\-space= " space "
.RS 1.2i
.TP 1.6i
freedbitmap
Freed bitmap
.TP
freedtable
Freed table
.TP
unallocbitmap
Unallocated bitmap
.TP
unalloctable
Unallocated table
.RE

.TP
.BI \-\-ad= " ad "
.RS 1.2i
.TP 1.6i
inicb
Allocation Descriptors in ICB
.TP
short
Short Allocation Descriptors
.TP
long
Long Allocation Descriptors
.RE

.TP
.B \-\-noefe
Don't Use Extended File Entries

.TP
.B \-\-locale
Treat ident string options as strings encoded according to current locale
settings (default). Must be specified as first argument.

.TP
.B \-\-u8
Treat ident string options as strings encoded in 8-bit OSTA Compressed Unicode
format, equivalent to Latin1 (ISO-8859-1). Must be specified as first argument.

.TP
.B \-\-u16
Treat ident string options as strings encoded in 16-bit OSTA Compressed Unicode
format, equivalent to UCS-2BE. Note that it is not possible to include zero
byte in command line options, therefore any character which has at least one
zero byte cannot be supplied (this applies to all Latin1 characters). Must be
specified as first argument.

.TP
.B \-\-utf8
Treat ident string options as strings encoded in UTF-8. Must be specified as
first argument.

.TP
.B \-\-closed
Make cdr media type closed (AVDP is written to start and also end of disk).
By default cdr media type is unclosed (AVDP is written only to start of disk).

.TP
.BI \-\-packetlen= " length "
Packet length in number of sectors for cdrw (default: 32 sectors)
and dvdrw (default: 16 sectors) media types.

.SH "EXIT STATUS"
.B mkudffs
returns 0 if successful, non-zero if there are problems.

.SH AUTHOR
.nf
Ben Fennema <bfennema@falcon.csc.calpoly.edu>
Pali Rohár <pali.rohar@gmail.com>
.fi

.SH AVAILABILITY
.B mkudffs
is part of the udftools package and is available from
https://github.com/pali/udftools/.
