.\" Copyright 2017 Vojtech Vladyka <vojtech.vladyka@gmail.com>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" References consulted:
.\"   
.\"
.\"
.TH UDFFSCK 8
.SH NAME
udffsck \- fsck for UDF filesystem
.SH SYNOPSIS
.B udffsck
[\fB\-vvvciph\fR]
[\fB\-B\fR \fIBLOCKSIZE\fR]
.IR medium
.SH DESCRIPTION
.B udffsck
checks and fixes UDF.
.PP 
.B DRAFT ONLY.
.PP
.SH OPTIONS
.TP
.BR \-B " " \fIBLOCKSIZE\fR
Force udffsck to use this blocksize instead of autodetection
Default is autodetected value by finding VRS and AVDP position.
.TP
.BR \-c
Only check medium and print found errors.
This is default behavior.
.TP
.BR \-i
Interactively fix medium. 
In this mode all corrections must be authorized by user.
.TP
.BR \-p
Automatical corrections. This is like 
.BR -i , 
but all questions are answered yes.
.TP
.BR \-h 
Short help message.
.TP
.BR \-v 
Warning verbosity level. 
Errors and warning will be printed.
.TP
.BR \-vv 
Message verbosity level. 
Errors, warnings and messages will be printed. 
Recomended for manual usage.
.TP
.BR \-vvv
Debug Verbosity level. 
Only for development and debug purposes. 
And for nosy users.
.SH EXAMPLES
Check medium and show it structure to user:
.PP
.nf
.RS
udffsck -vvc /dev/sda2 
.RE
.fi
.PP
Check and fix medium image automatically, show only errors:
.PP
.nf
.RS
udffsck -p udf_image_file.img 
.RE
.fi
.PP
.SH REPORTING BUGS
bla bla bla
.SH AUTHOR
This version of 
.B udffsck 
was written by Vojtech Vladyka <vojtech.vladyka@gmail.com>
